# Generated by Django 4.2 on 2023-06-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.CharField(max_length=100, verbose_name='Чат:')),
                ('message', models.TextField(verbose_name='Повідомлення')),
                ('time', models.TimeField(verbose_name='Час відправки:')),
            ],
        ),
    ]
