# Generated by Django 4.2 on 2023-06-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.CharField(max_length=75, verbose_name='Від')),
                ('to_user', models.CharField(max_length=75, verbose_name='Кому')),
                ('message', models.TextField(verbose_name='Повідомлення')),
                ('time', models.TimeField(verbose_name='Час відправки:')),
            ],
        ),
    ]
