# Generated by Django 4.2 on 2023-06-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='from_user',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Повідомлення від:'),
        ),
    ]
