# Generated by Django 4.2 on 2023-08-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='user1_is_online',
            field=models.BooleanField(null=True, verbose_name='<django.db.models.fields.related_descriptors.ForwardManyToOneDescriptor object at 0x000001EE82EC7490>'),
        ),
        migrations.AddField(
            model_name='chat',
            name='user2_is_online',
            field=models.BooleanField(null=True, verbose_name='<django.db.models.fields.related_descriptors.ForwardManyToOneDescriptor object at 0x000001EE82EC7710>'),
        ),
    ]
