# Generated by Django 4.2 on 2023-08-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat_user1_is_online_chat_user2_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='user1_is_online',
            field=models.BooleanField(null=True, verbose_name='<django.db.models.fields.related_descriptors.ForwardManyToOneDescriptor object at 0x0000019020BD3850>'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='user2_is_online',
            field=models.BooleanField(null=True, verbose_name='<django.db.models.fields.related_descriptors.ForwardManyToOneDescriptor object at 0x0000019020BD38D0>'),
        ),
    ]
