# Generated by Django 4.2 on 2023-06-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_messages_from_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='id_message',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Id-шник'),
        ),
    ]
