# Generated by Django 4.2 on 2023-08-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chat_user1_is_online_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='user1_is_online',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Перший юзер онлайн?'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='user2_is_online',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Другий юзер онлайн?'),
        ),
    ]
