# Generated by Django 4.2.3 on 2023-07-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_messages_from_user_remove_messages_id_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Час відправки:'),
        ),
    ]
