# Generated by Django 4.2 on 2023-08-29 09:28

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chat_user1_is_online_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=chat.models.image_upload_path, verbose_name='Відео'),
        ),
    ]
